export const BUILT_IN_EXERCISES = {
  Push: [
    {
      name: "Bench Press",
      sets: 4,
      reps: "8-10",
      muscle: "Chest",
      difficulty: "Intermediate",
    },
    {
      name: "Incline Dumbbell Press",
      sets: 3,
      reps: "10-12",
      muscle: "Chest",
      difficulty: "Intermediate",
    },
    {
      name: "Cable Fly",
      sets: 3,
      reps: "12-15",
      muscle: "Chest",
      difficulty: "Beginner",
    },
    {
      name: "Shoulder Press",
      sets: 4,
      reps: "8-10",
      muscle: "Shoulders",
      difficulty: "Intermediate",
    },
    {
      name: "Arnold Press",
      sets: 3,
      reps: "10-12",
      muscle: "Shoulders",
      difficulty: "Intermediate",
    },
    {
      name: "Lateral Raises",
      sets: 4,
      reps: "15-20",
      muscle: "Shoulders",
      difficulty: "Beginner",
    },
    {
      name: "Front Raises",
      sets: 3,
      reps: "12-15",
      muscle: "Shoulders",
      difficulty: "Beginner",
    },
    {
      name: "Tricep Pushdown",
      sets: 3,
      reps: "12-15",
      muscle: "Triceps",
      difficulty: "Beginner",
    },
    {
      name: "Skull Crushers",
      sets: 3,
      reps: "10-12",
      muscle: "Triceps",
      difficulty: "Intermediate",
    },
    {
      name: "Overhead Tricep Extension",
      sets: 3,
      reps: "12-15",
      muscle: "Triceps",
      difficulty: "Beginner",
    },
    {
      name: "Push-Ups",
      sets: 3,
      reps: "15-20",
      muscle: "Chest",
      difficulty: "Beginner",
    },
    {
      name: "Dips",
      sets: 3,
      reps: "10-15",
      muscle: "Triceps",
      difficulty: "Intermediate",
    },
  ],
  Pull: [
    {
      name: "Pull-Ups",
      sets: 4,
      reps: "6-10",
      muscle: "Back",
      difficulty: "Intermediate",
    },
    {
      name: "Lat Pulldown",
      sets: 4,
      reps: "10-12",
      muscle: "Back",
      difficulty: "Beginner",
    },
    {
      name: "Barbell Row",
      sets: 4,
      reps: "8-10",
      muscle: "Back",
      difficulty: "Intermediate",
    },
    {
      name: "Seated Cable Row",
      sets: 3,
      reps: "10-12",
      muscle: "Back",
      difficulty: "Beginner",
    },
    {
      name: "Single-Arm Dumbbell Row",
      sets: 3,
      reps: "10-12 each",
      muscle: "Back",
      difficulty: "Beginner",
    },
    {
      name: "T-Bar Row",
      sets: 3,
      reps: "10-12",
      muscle: "Back",
      difficulty: "Intermediate",
    },
    {
      name: "Face Pulls",
      sets: 4,
      reps: "15-20",
      muscle: "Rear Delts",
      difficulty: "Beginner",
    },
    {
      name: "Barbell Curl",
      sets: 3,
      reps: "10-12",
      muscle: "Biceps",
      difficulty: "Beginner",
    },
    {
      name: "Hammer Curls",
      sets: 3,
      reps: "12-15",
      muscle: "Biceps",
      difficulty: "Beginner",
    },
    {
      name: "Incline Dumbbell Curl",
      sets: 3,
      reps: "12-15",
      muscle: "Biceps",
      difficulty: "Beginner",
    },
    {
      name: "Preacher Curl",
      sets: 3,
      reps: "10-12",
      muscle: "Biceps",
      difficulty: "Intermediate",
    },
    {
      name: "Cable Curl",
      sets: 3,
      reps: "12-15",
      muscle: "Biceps",
      difficulty: "Beginner",
    },
  ],
  Legs: [
    {
      name: "Back Squat",
      sets: 4,
      reps: "6-8",
      muscle: "Quads",
      difficulty: "Intermediate",
    },
    {
      name: "Front Squat",
      sets: 3,
      reps: "8-10",
      muscle: "Quads",
      difficulty: "Advanced",
    },
    {
      name: "Leg Press",
      sets: 4,
      reps: "12-15",
      muscle: "Quads",
      difficulty: "Beginner",
    },
    {
      name: "Romanian Deadlift",
      sets: 4,
      reps: "10-12",
      muscle: "Hamstrings",
      difficulty: "Intermediate",
    },
    {
      name: "Leg Curl",
      sets: 3,
      reps: "12-15",
      muscle: "Hamstrings",
      difficulty: "Beginner",
    },
    {
      name: "Bulgarian Split Squat",
      sets: 3,
      reps: "10-12 each",
      muscle: "Glutes",
      difficulty: "Intermediate",
    },
    {
      name: "Hip Thrust",
      sets: 4,
      reps: "12-15",
      muscle: "Glutes",
      difficulty: "Beginner",
    },
    {
      name: "Walking Lunges",
      sets: 3,
      reps: "12 each",
      muscle: "Glutes",
      difficulty: "Beginner",
    },
    {
      name: "Standing Calf Raise",
      sets: 4,
      reps: "20-25",
      muscle: "Calves",
      difficulty: "Beginner",
    },
    {
      name: "Seated Calf Raise",
      sets: 3,
      reps: "15-20",
      muscle: "Calves",
      difficulty: "Beginner",
    },
    {
      name: "Leg Extension",
      sets: 3,
      reps: "15-20",
      muscle: "Quads",
      difficulty: "Beginner",
    },
    {
      name: "Sumo Deadlift",
      sets: 4,
      reps: "6-8",
      muscle: "Hamstrings",
      difficulty: "Intermediate",
    },
  ],
  Core: [
    {
      name: "Plank",
      sets: 3,
      reps: "60s",
      muscle: "Core",
      difficulty: "Beginner",
    },
    {
      name: "Side Plank",
      sets: 3,
      reps: "45s each",
      muscle: "Obliques",
      difficulty: "Beginner",
    },
    {
      name: "Cable Crunch",
      sets: 3,
      reps: "15-20",
      muscle: "Abs",
      difficulty: "Beginner",
    },
    {
      name: "Hanging Leg Raise",
      sets: 3,
      reps: "12-15",
      muscle: "Lower Abs",
      difficulty: "Intermediate",
    },
    {
      name: "Ab Wheel Rollout",
      sets: 3,
      reps: "10-12",
      muscle: "Core",
      difficulty: "Intermediate",
    },
    {
      name: "Russian Twists",
      sets: 3,
      reps: "20 each",
      muscle: "Obliques",
      difficulty: "Beginner",
    },
    {
      name: "Dragon Flag",
      sets: 3,
      reps: "6-8",
      muscle: "Core",
      difficulty: "Advanced",
    },
    {
      name: "Decline Sit-Up",
      sets: 3,
      reps: "15-20",
      muscle: "Abs",
      difficulty: "Beginner",
    },
    {
      name: "Bicycle Crunches",
      sets: 3,
      reps: "20 each",
      muscle: "Obliques",
      difficulty: "Beginner",
    },
    {
      name: "Pallof Press",
      sets: 3,
      reps: "12-15",
      muscle: "Core",
      difficulty: "Beginner",
    },
  ],
  Cardio: [
    {
      name: "Treadmill Run",
      sets: 1,
      reps: "20-30min",
      muscle: "Full Body",
      difficulty: "Beginner",
    },
    {
      name: "Rowing Machine",
      sets: 1,
      reps: "15-20min",
      muscle: "Full Body",
      difficulty: "Beginner",
    },
    {
      name: "Jump Rope",
      sets: 5,
      reps: "2min",
      muscle: "Full Body",
      difficulty: "Beginner",
    },
    {
      name: "Cycling",
      sets: 1,
      reps: "30min",
      muscle: "Legs",
      difficulty: "Beginner",
    },
    {
      name: "Box Jumps",
      sets: 4,
      reps: "10",
      muscle: "Legs",
      difficulty: "Intermediate",
    },
    {
      name: "Battle Ropes",
      sets: 5,
      reps: "30s",
      muscle: "Full Body",
      difficulty: "Intermediate",
    },
    {
      name: "Burpees",
      sets: 4,
      reps: "15",
      muscle: "Full Body",
      difficulty: "Intermediate",
    },
    {
      name: "Stair Climber",
      sets: 1,
      reps: "20min",
      muscle: "Legs",
      difficulty: "Beginner",
    },
  ],
  Olympic: [
    {
      name: "Deadlift",
      sets: 4,
      reps: "4-6",
      muscle: "Full Body",
      difficulty: "Advanced",
    },
    {
      name: "Power Clean",
      sets: 4,
      reps: "4-5",
      muscle: "Full Body",
      difficulty: "Advanced",
    },
    {
      name: "Snatch",
      sets: 4,
      reps: "3-4",
      muscle: "Full Body",
      difficulty: "Advanced",
    },
    {
      name: "Clean & Jerk",
      sets: 3,
      reps: "3-4",
      muscle: "Full Body",
      difficulty: "Advanced",
    },
    {
      name: "Overhead Squat",
      sets: 3,
      reps: "5-6",
      muscle: "Full Body",
      difficulty: "Advanced",
    },
  ],
};

export const CATEGORY_META = {
  Push: { emoji: "💪", color: "#00875A" },
  Pull: { emoji: "🏋️", color: "#D94F00" },
  Legs: { emoji: "🦵", color: "#6D28D9" },
  Core: { emoji: "🔥", color: "#B45309" },
  Cardio: { emoji: "🏃", color: "#BE185D" },
  Olympic: { emoji: "🥇", color: "#1D4ED8" },
  Custom: { emoji: "⚡", color: "#00875A" },
};

export const SUGGESTIONS = [
  {
    type: "Push",
    reason: "💪 Chest & shoulders are well-rested — great day to push heavy!",
    emoji: "💪",
  },
  {
    type: "Pull",
    reason: "🏋️ Back and biceps need attention for balanced development.",
    emoji: "🏋️",
  },
  {
    type: "Legs",
    reason: "🦵 Leg day! The most rewarding session you'll ever dread.",
    emoji: "🦵",
  },
  {
    type: "Core",
    reason: "🔥 A strong core improves every lift — time to burn!",
    emoji: "🔥",
  },
  {
    type: "Cardio",
    reason: "🏃 Active recovery — get that heart rate pumping!",
    emoji: "🏃",
  },
];
